apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  selector:
    matchLabels:
      app: tempo
  replicas: 1
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: tempo
          args:
            - -config.file=/etc/tempo.yaml
          ports:
            - name: otlp-http
              containerPort: 4318
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  ports:
    - protocol: TCP
      port: 4318
      targetPort: otlp-http
    
